### ISSUE TITLE
Issue rendering HAR file with redirects

### ISSUE THREAD

**Issue by vic0707** [micmro/PerfCascade#177]
PerfCascade is not able to display the attached HAR file. It gives the following message:

`TypeError: Cannot read property 'request' of undefined
    at g (https://micmro.github.io/PerfCascade/src/perf-cascade.min.js:3:5511)
    at Object.i [as documentIsSecure] (https://micmro.github.io/PerfCascade/src/perf-cascade.min.js:3:5725)
    at Object.g [as transformPage] (https://micmro.github.io/PerfCascade/src/perf-cascade.min.js:3:9928)
    at https://micmro.github.io/PerfCascade/src/perf-cascade.min.js:3:9162
    at Array.map (native)
    at Object.d [as transformDoc] (https://micmro.github.io/PerfCascade/src/perf-cascade.min.js:3:9135)
    at Object.e [as fromHar] (https://micmro.github.io/PerfCascade/src/perf-cascade.min.js:2:30514)
    at renderPerfCascadeChart (https://micmro.github.io/PerfCascade/src/demo-page.js:38:38)
    at https://micmro.github.io/PerfCascade/src/demo-page.js:72:9
    at d (https://micmro.github.io/PerfCascade/src/perf-cascade-file-reader.min.js:3:1785)`

[redirect.har.zip](https://github.com/micmro/PerfCascade/files/828340/redirect.har.zip)

**Comment by micmro** [comment]
Thanks for filing this. Had not consider redirects without a final page - fixed with `v0.9.1`
