### ISSUE TITLE
can we use this package in nodejs ??

### ISSUE THREAD

**Issue by surya0014** [micmro/PerfCascade#248]
I tried installing Perf-cascade package in node server, installation  was  successful
npm install perf-cascade
 But  while calling fromHar() I obtain the  following error :

(function (exports, require, module, __filename, __dirname) { export * from "./lib/main"; 
                                                                                                 ^^^^
SyntaxError: Unexpected token export
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

**Comment by micmro** [comment]
PerfCascade will only work in the browser as it need the [DOM](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction).
